### ISSUE TITLE
Now Playing/Library bug fix

### ISSUE THREAD

**Issue by BBaoVanC** [usenocturne/nocturne-ui#12]
See https://discord.com/channels/1304909652387172493/1306836563044339793.

> I keep getting "Application error: a client-side error has occurred (see the browser console for more information)."
>
> Video Link: https://drive.google.com/file/d/18YkEvxl5Q4X0jN0NjLAT3Ac2agksmIHh/view?usp=sharing

**Comment by brandonsaldan** [comment]
fixed in v2.0.0-beta.2: https://github.com/usenocturne/nocturne-ui/pull/14
