### ISSUE TITLE
Select Spotify Connect device

### ISSUE THREAD

**Issue by itsnebulalol** [usenocturne/nocturne-ui#21]

**Comment by kenhayward** [comment]
The spotify API offers **Get Available Devices** and **Transfer Playback** endpoints so this might be possible, an icon on the Now Playing screen would be very cool, with a pop up draw like for **add to playlist**. The Get Available Devices endpoint does include the device type although might need some experimentation as it doesn't supply a full list of device type options

**Comment by vakst** [comment]
Please consider the pull request https://github.com/usenocturne/nocturne-ui/pull/60 before starting working on that issue.
