### ISSUE TITLE
Ability to select menu UI with physical scroll button click

### ISSUE THREAD

**Issue by b16tran** [usenocturne/nocturne-ui#24]
Scrolling works but clicking doesn't select. Ideally would like the UI to be more physical button centric with navigation vs touch controls.

**Comment by brandonsaldan** [comment]
fixed in 21dc3ff994584f0f2a831fc265a85e6f73593d91, a51d5f761eabea8244d5deed00b6ae61181b3957, d39793fdf88c1859278af915eb6cddab6fb0192d. thank you!
