### ISSUE TITLE
Adjusting volume of playback through phone

### ISSUE THREAD

**Issue by b16tran** [usenocturne/nocturne-ui#25]
When scrolling with the wheel, the volume does not change when phone is playback device. Volume overlay appears and adjusts but resets back to max volume and has no affect.

Using iPhone 16 Pro

Tested with using another device as playback and volume adjusted correctly.

**Comment by brandonsaldan** [comment]
looking at the [devices documentation](https://developer.spotify.com/documentation/web-api/reference/get-a-users-available-devices) with playback coming through a phone, it seems as though the api disallows this via the `supports_volume` flag:

response from an iphone:

```
{
  "devices" : [ {
    "id" : "xxxx",
    "is_active" : true,
    "is_private_session" : false,
    "is_restricted" : false,
    "name" : "iPhone",
    "supports_volume" : false,
    "type" : "Smartphone",
    "volume_percent" : 100
  } ]
}
```

response from an android:

```
{
  "devices" : [ {
    "id" : "xxxx",
    "is_active" : true,
    "is_private_session" : false,
    "is_restricted" : false,
    "name" : "Pixel 8",
    "type" : "Smartphone",
    "volume_percent" : 100
    "supports_volume" : false,
  } ]
}
```

compared to the response from a PC:

```
{
  "devices" : [ {
    "id" : "xxxx",
    "is_active" : true,
    "is_private_session" : false,
    "is_restricted" : false,
    "name" : "PC",
    "supports_volume" : true,
    "type" : "Computer",
    "volume_percent" : 100
  } ]
}
```

seems like a very unfortunate limitation on spotify's end, so there isn't much we can do about this currently; it may be possible through bluetooth and we'll cycle back to it when the time comes!
