### ISSUE TITLE
Clicking back button in menu takes you to now playing

### ISSUE THREAD

**Issue by b16tran** [usenocturne/nocturne-ui#26]
No matter where I am in the UI, I usually clicked the back (bottom right) button several times to exit everything and just get back to the now playing screen

**Comment by brandonsaldan** [comment]
Should be fixed in v2.1.0-beta.2, please let me kno!

**Comment by b16tran** [comment]
Not working for me. It jumps back to the recents tab if i'm on other tabs though

**Comment by brandonsaldan** [comment]
fixed in eac766bcbff4e328a2d5afdc36b9f5e2419fc986, thank you!
