### ISSUE TITLE
Scrolling doesn't work in menu screen until carousel is touched

### ISSUE THREAD

**Issue by b16tran** [usenocturne/nocturne-ui#42]
Carousel selection isn't active until you interact with it by touching. Aka if I select Library, I expect to be able to start scrolling. I should always be able to scroll on the current tab selected.

Or by default the scroll knob should switch between the tabs on the left and when knob button pressed, goes into the carousel on the right from which you can scroll. Then if you click back, it goes back to the tabs for scrolling. There already is the little line on the left indicating the active tab, that can be extended to move over to above the album art when you enter the carousel context.

**Comment by BBaoVanC** [comment]
I think what's happening is that the cursor is at the position where you last tapped. Then, if the component that should be scrolled by the dial doesn't happen to be under that spot, scrolling doesn't work. Perhaps nocturne-ui should override scroll wheel events and redirect them to whichever should be the main, scrollable component on the current page.
