### ISSUE TITLE
Clicking saved playlist button should take me to Now Playing screen if in menus

### ISSUE THREAD

**Issue by b16tran** [usenocturne/nocturne-ui#43]

**Comment by brandonsaldan** [comment]
would you be able to describe this some more? which menus do you mean?

**Comment by b16tran** [comment]
Clicking the playlist shortcuts (physical top buttons) currently stay in the current screen you're on.

If I'm in the menus, I would expect it to then take me to the currently playing song.

**Comment by brandonsaldan** [comment]
fixed in 626029c, change will be live in our 3.0.0 update. thanks for creating this issue!!
