### ISSUE TITLE
Paused song should stay persistent

### ISSUE THREAD

**Issue by b16tran** [usenocturne/nocturne-ui#58]
Currently now playing screen becomes empty a few seconds after pausing a song.

**Comment by itsnebulalol** [comment]
Is it actually after a few seconds or is it actually ~1 minute or higher? Spotify Connect *does* have a timeout.

**Comment by b16tran** [comment]
Less than 10 seconds. Is it tied to how long the iPhone keeps displaying it?

**Comment by b16tran** [comment]
There's no way to store the current song + time and start (not resume) a session from there?

Ok. I don't know how nocturne fully works but I thought it was only using the phone's hotspot and had nothing to do with the Spotify app itself. That nocturne is talking to the api/internet vs talking directly to the phone.

Factory CarPlay kept it displayed.
