### ISSUE TITLE
E019: Failed to execute 'json' on 'Response': Unexpected end of JSON input

### ISSUE THREAD

**Issue by vakst** [usenocturne/nocturne-ui#65]
![JSON error](https://github.com/user-attachments/assets/0fbd1ba2-9ec0-49e0-889a-f4c123b68945)

An error occurs when no active players are available. The code is trying to parse the JSON response from the API https://api.spotify.com/v1/me/player.

**Comment by brandonsaldan** [comment]
works perfect, thank you so much!!!!
